### ISSUE TITLE
need solution of these questions

### ISSUE THREAD

**Issue by kishan779** [kishan779/DSA_ques#4]
https://leetcode.com/problems/valid-parentheses/
https://leetcode.com/problems/maximum-subarray/
https://leetcode.com/problems/search-a-2d-matrix/
https://leetcode.com/problems/permutations/
https://leetcode.com/problems/search-in-rotated-sorted-array/
https://leetcode.com/problems/reverse-linked-list/
https://leetcode.com/problems/top-k-frequent-elements/
https://leetcode.com/problems/decode-string/
https://leetcode.com/problems/reorganize-string/
https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/
https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/
https://leetcode.com/problems/minimum-window-substring/
https://leetcode.com/problems/best-time-to-buy-and-sell-stock-iii/
https://leetcode.com/problems/integer-to-english-words/
https://leetcode.com/problems/concatenated-words/
https://leetcode.com/problems/two-sum/
https://leetcode.com/problems/majority-element/
https://leetcode.com/problems/spiral-matrix/
https://leetcode.com/problems/product-of-array-except-self/
https://leetcode.com/problems/word-search/
https://leetcode.com/problems/find-the-duplicate-number/
https://leetcode.com/problems/k-diff-pairs-in-an-array/
https://leetcode.com/problems/subarray-sums-divisible-by-k/
https://leetcode.com/problems/first-missing-positive/
https://leetcode.com/problems/max-value-of-equation/
https://leetcode.com/problems/word-break/
https://leetcode.com/problems/knight-dialer/
https://leetcode.com/problems/unique-paths/
https://leetcode.com/problems/longest-arithmetic-subsequence/
https://leetcode.com/problems/regular-expression-matching/
https://leetcode.com/problems/longest-valid-parentheses/
https://leetcode.com/problems/minimum-difficulty-of-a-job-schedule/
https://leetcode.com/problems/minimum-cost-to-cut-a-stick/
https://leetcode.com/problems/implement-strstr/
https://leetcode.com/problems/minimum-remove-to-make-valid-parentheses/
https://leetcode.com/problems/basic-calculator-ii/
https://leetcode.com/problems/power-of-two/
https://leetcode.com/problems/string-to-integer-atoi/
https://leetcode.com/problems/max-points-on-a-line/
https://leetcode.com/problems/remove-k-digits/
https://leetcode.com/problems/clone-graph/
https://leetcode.com/problems/house-robber-iii/
https://leetcode.com/problems/critical-connections-in-a-network/
https://leetcode.com/problems/diameter-of-binary-tree/
https://leetcode.com/problems/redundant-connection/
https://leetcode.com/problems/redundant-connection-ii/
https://leetcode.com/problems/capacity-to-ship-packages-within-d-days/
https://leetcode.com/problems/rotting-oranges/
https://leetcode.com/problems/longest-repeating-character-replacement/
https://leetcode.com/problems/lru-cache/

**Comment by ShishuSidharth** [comment]
how many do we need to solve?

**Comment by aashish-1904** [comment]
Hello, can i contribute the answers to a few of these questions?
If so, then I'd like to do this task

**Comment by kishan779** [comment]
> how many do we need to solve?

2 question minimum

**Comment by kishan779** [comment]
closed this issue
